### ISSUE TITLE
Potentially unnecessary binary files on generate

### ISSUE THREAD

**Issue by danfang** [RobertCraigie/prisma-client-py#370]
## Bug description

In a basic Docker container:
```
FROM python:3.8
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY schema.prisma schema.prisma
RUN prisma generate
COPY . .
CMD ["python3", "main.py"]
```

I was inspecting the Docker container file size using `dive`. Looking in the `/tmp` folder it looks like there may be some unused binaries. It appears that the binaries used are in `/tmp/prisma/binaries/engines/<version>` according to [constants.py](https://github.com/RobertCraigie/prisma-client-py/blob/main/src/prisma/binaries/constants.py#L41).

There is another folder `/tmp/prisma-binaries` with 114MB of binaries with the same name, but is missing the `prisma-cli-linux` but includes the others, e.g. `prisma-query-engine-debian-openssl-1.1.x`. If I remove this folder, the prisma query engine still appears to work.

It may be that the prisma generate and binary download process is downloading duplicate files.

## How to reproduce

```
docker build --platform linux/amd64 -t test-prisma
dive test-prisma
```

## Environment & setup

- OS: MacOS Docker building for linux/amd64
- Database: 
- Python version: 3.8
- Prisma version: prisma==0.6.4

**Comment by RobertCraigie** [comment]
Thanks for the report.

It is completely safe to remove the `/tmp/prisma-binaries` folder as Prisma Client Python doesn't use it and that directory is only created when running the packaged Prisma CLI (which is what we make use of) as it is also not used by Prisma themselves. Reference: https://github.com/prisma/prisma/blob/main/packages/sdk/src/resolveBinary.ts#L84-L108.

For some context this came about due to issues with the virtual file system that [pkg](https://github.com/vercel/pkg) uses. If we wanted to keep the same behaviour as the node Prisma client which downloads the binaries directly into `node_modules` we would have to download binaries for *every* supported platform and then package that into the CLI binary. As far as I am aware the `/tmp/prisma-binaries` solution was an attempt to work around this although it was never fully implemented.

cc @janpio The only potential issue I can see with migrating to use `/tmp/prisma-binaries` instead of manually downloading the binaries is that it's not prefixed by a version hash which means it would break if multiple projects using Prisma are used on the same machine and are on different Prisma versions.

I'm thinking it might be possible to instead use the `~/.cache/prisma/master/<hash>/<platform>` directory instead and somehow disable the code path that copies the binaries into `node_modules` if we're in a packaged context. That solution is still not ideal however as an ideal solution (#22) would mean that Prisma Client Python doesn't have do any platform detection apart from for resolving the CLI binary which is much less complicated. Maybe Prisma could create a symlink when the binaries are downloaded e.g. `~/.cache/prisma/master/<hash>/native` that would point to the current platform directory.
