### ISSUE TITLE
Table not found error with SQLite

### ISSUE THREAD

**Issue by karrycreativ** [RobertCraigie/prisma-client-py#396]
## Bug description

When trying to create a database entry I get the following result:
"The table `main.MenuItem` does not exist in the current database."

## How to reproduce

I'm using FastApi and Uvicorn
The script is run from routes.api.v1.endpoints.menu

### Script:
```python
@router.post("/")
async def handler():
    try:
        await prisma.connect()
        item = await prisma.menuitem.create(data={
            'item_name': 'Test',
            'price': 1.2
        })
        return item
    except Exception as ex:
        print(ex)
        return str(ex)
    finally:
        await prisma.disconnect()
```
### My Directory Structure
```
.
├── __init__.py
├── app.py
├── db
│   ├── client.py
│   ├── dev.db
│   └── prisma
│       ├── migrations
│       └── schema.prisma
├── requirements.txt
└── routes
    ├── __init__.py
    └── api
        ├── __init__.py
        └── v1
            ├── __init__.py
            ├── endpoints
            │   ├── __init__.py
            │   └── menu.py
            └── router.py
```

## Prisma information

```prisma

generator client {
  provider = "prisma-client-py"
}

datasource db {
  provider = "sqlite"
  url      = "file:../dev.db"
}

model MenuItem {
  id        Int    @id @default(autoincrement())
  item_name String
  price     Float
}

```

## Environment & setup

- OS: Ubuntu20.04
- Database: SQLite
- Python version: 3.10
- Prisma version:

```
prisma               : 3.13.0
prisma client python : 0.6.5
platform             : debian-openssl-1.1.x
engines              : efdf9b1183dddfd4258cd181a72125755215ab7b
install path         : /home/karry/projects/clients/idhb/.venv/lib/python3.10/site-packages/prisma
installed extras     : []
```

**Comment by RobertCraigie** [comment]
Thank you for the very detailed issue!

I suspect this is due to issues with relative paths to SQLite databases. If I remember correctly, the client will use the path relative to the current working directory when you run any queries and the migration engine will use paths relative to the schema.

To workaround this you can explicitly set the path to the SQLite database you want to use: https://prisma-client-py.readthedocs.io/en/stable/reference/client/#datasource-overriding

In your case, it looks you're instantiating the Prisma Client in `db/client.py` right? If you are then you should use something like this:

```py
from pathlib import Path

prisma = Prisma(
    datasource={
        'url': f'file:{Path(__file__).parent / "dev.db"}'
    },
)
```

Also as an aside you should only run `prisma.connect()` once in your application lifecycle as Prisma handles a connection pool for you, see this example for how to do that with FastAPI: https://github.com/RobertCraigie/prisma-client-py/blob/c988de2b1ee79124d6a65376492a4b9caaa0ea27/examples/fastapi-basic/main.py#L15-L23

Let me know if you have any more questions!

**Comment by karrycreativ** [comment]
@RobertCraigie Thank you so so much for your quick response. I knew I was missing something but I could not figure it out for the life of me! I made your changes and it works now! 

Thank you for correction on the connection as well. I made that fix also.
