### ISSUE TITLE
Decimal breaks sqlserver schema

### ISSUE THREAD

**Issue by nitedani** [RobertCraigie/prisma-client-py#418]
## Bug description

prisma generate produces no output, the prisma client is not generated with the following schema:

## How to reproduce

prisma generate

## Expected behavior

The prisma client is generated

## Prisma information

```prisma
datasource db {
  provider = "sqlserver"
  url      = ""
}

generator db {
  provider  = "prisma-client-py"
  interface = "asyncio"
}

model Test {
  id    Int     @id
  value Decimal
}
```

## Environment & setup

- OS: Windows 11
- Database: SQL Server
- Python version: 3.8.10
- Prisma version: 3.13.0

```
prisma               : 3.13.0
prisma client python : 0.6.6
platform             : windows
engines              : efdf9b1183dddfd4258cd181a72125755215ab7b
install path         : C:\Users\x\AppData\Local\Programs\Python\Python38\Lib\site-packages\prisma
installed extras     : []
```

**Comment by RobertCraigie** [comment]
Hi @nitedani, this behaviour is intentional as support for the Decimal type is still experimental due to some limitations, see #106 for more details. You need to set the `enable_experimental_decimal` config option to `true` to enable it.

Normally a detailed error message would be output that explains this situation but unfortunately due to https://github.com/prisma/prisma/issues/10270 this is not the case on Windows.

Please reopen if you need any more help!
