### ISSUE TITLE
Ensure multi schema models work

### ISSUE THREAD

**Issue by RobertCraigie** [RobertCraigie/prisma-client-py#589]
## Problem

Prisma added [preview feature support](https://github.com/prisma/prisma/issues/1122#issuecomment-1231773471) for `multiSchema` in `v4.3.0`, we should make sure this works for Prisma Client Python.

## Suggested solution

Write tests. I suspect this will already be supported.

**Comment by Xmaster6y** [comment]
I noted this doesn't work, does anyone confirm?

## Reproduce

My schema works with `prisma` 5.15 in `js`. To reproduce here is a super simple that doesn't work:

```prisma
// prisma/schema/main.prisma
generator client {
  provider = "prisma-client-py"
  previewFeatures = ["prismaSchemaFolder"]
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.sqlite"
}
```

```prisma
// prisma/schema/user.prisma
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

## Error

This leads to a `shutil` error `IsADirectoryError` due to `prisma/generator/generator.py", line 242, in generate`

```py
shutil.copy(data.schema_path, packaged_schema)
```
in `prisma/generator/generator.py", line 160, in _on_request`
```py
self.generate(data)
```

I might explore this in the coming months.

**Comment by RobertCraigie** [comment]
I can reproduce that error, working on a fix.
