### ISSUE TITLE
Generate sqlalchemy models

### ISSUE THREAD

**Issue by mr-bjerre** [RobertCraigie/prisma-client-py#69]
You've been busy here - very cool. 

I'm afraid that many people would be very careful about moving to a new ORM in python - have you considered generate from prisma to sqlalchemy models instead (or as well)? 

Btw. how did you figure out how to build a python generator for prisma? I can't seem to find any docs anywhere

**Comment by RobertCraigie** [comment]
> have you considered generate from prisma to sqlalchemy models instead (or as well)?

I will not generate SQLAlchemy models as well, I do not see this providing any real value as you might as well just write your database models in SQLAlchemy instead of using Prisma as a middleman.

> Btw. how did you figure out how to build a python generator for prisma? I can't seem to find any docs anywhere

I figured out how to build a python generator by reading through the https://github.com/prisma/prisma-client-go code, however this goes very deep into the prisma internals, if you're wanting to write your own generator in python I am working on making that very easy with #42

**Comment by mr-bjerre** [comment]
> I will not generate SQLAlchemy models as well, I do not see this providing any real value as you might as well just write your database models in SQLAlchemy instead of using Prisma as a middleman.

We have a monorepo with different languages - e.g. node and python. So we'd have prisma client in node and sqlalchemy in python - based of the same schema.prisma. I'm sure your ORM will be great but stability is really important - obviously you can't guarantee that at this point. 

> I figured out how to build a python generator by reading through the https://github.com/prisma/prisma-client-go code, however this goes very deep into the prisma internals, if you're wanting to write your own generator in python I am working on making that very easy with #42

Yeah I figured it has been quite the journey. I'm excited to follow #42 and your progress here in general!

**Comment by RobertCraigie** [comment]
> We have a monorepo with different languages

I hadn't considered that, that's a good use case.

I still don't think I'm going to generate SQLAlchemy models as well simply due to the complexity this would introduce and the primary benefit would only really be useful while the python client is not stable and I would rather work on getting the client stable.

After #42 is implemented a community generator could easily be created though.

> I'm excited to follow #42 and your progress here in general!

Thank you!

**Comment by mr-bjerre** [comment]
That sounds very reasonable. Thank you for your responses!

**Comment by RobertCraigie** [comment]
@mr-bjerre I've just released `v0.4.1` which adds support for custom Prisma generators, if you wanted to try out creating a custom generator for SQLAlchemy models I would be more than happy to help.

https://github.com/RobertCraigie/prisma-client-py/releases/tag/v0.4.1

**Comment by mr-bjerre** [comment]
Yeah I noticed 🙏🏼🙏🏼


But I actually ended up building a node application for that part instead so currently no need for it. 

But great to see your progress
