### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by danielweil** [RobertCraigie/prisma-client-py#72]
Hi, Great Work!

I want to use this lib with NextJS using python as the serverless runtime language. I use Windows as my development environment. I saw Windows is not supported. Does that mean it won't work for me? Is there any plans to support it in the future?

Thanks!

**Comment by RobertCraigie** [comment]
Windows is unofficially supported, there is code in the library specifically targeting windows but we don't currently run any tests on it.

There are plans to add support for windows in the future.

In regards to serverless, I have not tested integration with any serverless framework and I have some doubts about it working right now due to how binaries are handled.

It would be a great help if you could give it a try and let me know if you encounter any errors, I will be happy to answer any questions you have.

Thank you!

**Comment by danielweil** [comment]
Will give it a try!

Thanks!

**Comment by RobertCraigie** [comment]
Closing as I've clarified windows support 2532aeb0cbfef21d752c811f4502602fe94243c6.

Please re-open or create a new issue if you experience any difficulties or have any more questions.
